---
version: 0.2

phases:
  build:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  packaging: ZIP
  files:
    - template-export.yml
