---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

  GoogleApiKey:
    Type: 'AWS::SSM::Parameter::Value<String>'
    NoEcho: true
    Description: Google API key from parameter store
    Default: google_api_key

Resources:
  CommuteTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: commute-traffic
      TopicName: commute-traffic

  TrafficToSns:
    Type: AWS::Serverless::Function
    Properties:
      Description: Commute Traffic to SNS
      Handler: index.handler
      Runtime: python2.7
      Timeout: 30
      Policies:
        - AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CommuteTopic
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
