---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  CommuteTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: commute-traffic
      TopicName: commute-traffic

  TrafficToSns:
    Type: AWS::Serverless::Function
    Properties:
      Description: Commute Traffic to SNS
      Handler: index.handler
      Runtime: python2.7
      CodeUri: ./
      Timeout: 30
      Policies:
        - AmazonSNSFullAccess
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CommuteTopic
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: 'cron(0/5 * * * ? *)'
            Input: '{"trigger": "cloudwatch"}'
